fix: mark `:db_termination` as shutdown
supabase/supavisor pull request #475
Opened 2024-11-09 09:14 UTC by hauleth

That will reduce amount of error logs related to unexpected process shutdown (as `db_termination` is rather expected shutdown).

2024-11-11 14:23 UTC, abc3 commented
But this won't terminate the linked client handler?

2024-11-11 14:24 UTC, abc3 requested changes
But this won't terminate the linked client handler?

2024-11-12 10:11 UTC, hauleth commented
@abc3 everything should work as expected there, as it only changes behaviour in the supervisor. Exit message is still sent and should be handled as is.

2024-11-12 16:27 UTC, abc3 approved these changes

2024-11-12 18:42 UTC, merged